# Generated by Django 3.2.9 on 2021-11-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0004_film_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('type', models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (1, 'Horror'), (0, 'Inne'), (3, 'Sci-fi'), (4, 'Drama')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='additional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmyweb.additionalinformation'),
        ),
    ]
