# Generated by Django 3.2.9 on 2021-11-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0006_auto_20211116_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (0, 'Inne'), (4, 'Drama'), (3, 'Sci-fi'), (1, 'Horror')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('films', models.ManyToManyField(to='filmyweb.Film')),
            ],
        ),
    ]
