# Generated by Django 3.2.9 on 2021-11-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0007_auto_20211116_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (2, 'Komedia'), (1, 'Horror'), (3, 'Sci-fi'), (0, 'Inne')], default=0),
        ),
    ]
